export const perfumes = [
    {
      id: 1,
      name: 'Celestial Bloom',
      description: 'A fresh and floral scent with notes of bergamot and jasmine',
      image: '/images/celestial-bloom.jpg',
      price: 85,
      badge: 'bestseller',
      category: 'Floral',
      notes: {
        top: ['Bergamot', 'Green Tea'],
        middle: ['Jasmine', 'Raspberry'],
        base: ['Sandalwood', 'White Musk'],
      },
    },
    {
      id: 2,
      name: 'Golden Dusk',
      description: 'Warm and spicy with ginger and caramel undertones',
      image: '/images/golden-dusk.jpg',
      price: 79,
      badge: 'bestseller',
      category: 'Gourmand',
      notes: {
        top: ['Grapefruit', 'Ginger'],
        middle: ['Caramel', 'Blackcurrant'],
        base: ['Coffee', 'Praline'],
      },
    },
    {
      id: 3,
      name: 'Passion Dance',
      description: 'Deep and sophisticated with spicy undertones',
      image: '/images/passion-dance.jpg',
      price: 89,
      badge: 'bestseller',
      category: 'Oriental',
      notes: {
        top: ['Pink Pepper', 'Cardamom'],
        middle: ['Vanilla', 'Almond'],
        base: ['Tonka Bean', 'Amber'],
      },
    },
    {
      id: 4,
      name: 'Ocean Whisper',
      description: 'Fresh and aquatic with notes of pear and basil',
      image: '/images/ocean-whisper.jpg',
      price: 79,
      badge: 'bestseller',
      category: 'Fresh',
      notes: {
        top: ['Pear', 'Basil'],
        middle: ['Lavender', 'Fig'],
        base: ['Cedarwood', 'Vetiver'],
      },
    },
    {
      id: 5,
      name: 'Amber Eclipse',
      description: 'A bold and magnetic fragrance with warm amber and exotic spice wrapped in creamy sweetness',
      image: '/images/amber-eclipse.jpg',
      price: 109,
      badge: 'new',
      category: 'Oriental',
      notes: {
        top: ['Saffron', 'Mandarin Peel'],
        middle: ['Rose', 'Oud'],
        base: ['Vanilla', 'Fig'],
      },
    },
    {
      id: 6,
      name: 'Fresh As Citrus',
      description: 'A vibrant and uplifting citrus fragrance bursting with sun-kissed energy and sparkling brightness',
      image: '/images/fresh-as-citrus.jpg',
      price: 79,
      badge: 'new',
      category: 'Citrus',
      notes: {
        top: ['Lemon', 'Mandarin'],
        middle: ['Orange Blossom', 'Basil'],
        base: ['Musk', 'Vetiver'],
      },
    },
  ];